### ISSUE TITLE
Showing menue is broken

### ISSUE THREAD

**Issue by drewjosh** [frickerg/mensajs#1]
Something is broken with the plugin, because when I type "mensajs" into my console and hit Enter, I see the following exception:

![Bildschirmfoto 2019-10-11 um 12 21 47](https://user-images.githubusercontent.com/32765631/66644725-f4675780-ec21-11e9-8466-d01fa522e6f3.png)

Steps to reproduce:
1. open console
2. type "mensajs"
3. Hit Enter

**Expected**:
A console message, something like: "Pizza Margarita", or something else that is delicious

**Actual**:
see Screenshot above

Please fix this issue as this is a very important part of the day!
Thanks!

**Comment by hessg1** [comment]
since @frickerg is busy doing rocket science, i did a quick fix - see pull request #2 🤓

**Comment by frickerg** [comment]
Pull request #2 has been merged, thank you both for your help 🎉

**Comment by drewjosh** [comment]
Thank you for the very satisfying fix @hessg1 😄
